// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPxpZVpbpqniI_vfexdk4eDPc1kfmQ4YI',
    appId: '1:994586725816:web:947ef7fb5a189be9e6d34d',
    messagingSenderId: '994586725816',
    projectId: 'photofiesta',
    authDomain: 'photofiesta.firebaseapp.com',
    storageBucket: 'photofiesta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHBmrL7CbtIH7rJlzjG4S6bmJ1MGeVrP0',
    appId: '1:994586725816:android:ad7793d32f891c3ce6d34d',
    messagingSenderId: '994586725816',
    projectId: 'photofiesta',
    storageBucket: 'photofiesta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM3cc6wmnJBSN34GcFJn-Zb7dElxFDE20',
    appId: '1:994586725816:ios:44d89d78c8977d64e6d34d',
    messagingSenderId: '994586725816',
    projectId: 'photofiesta',
    storageBucket: 'photofiesta.appspot.com',
    iosBundleId: 'com.example.photofiesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM3cc6wmnJBSN34GcFJn-Zb7dElxFDE20',
    appId: '1:994586725816:ios:20ba2baebd8bce79e6d34d',
    messagingSenderId: '994586725816',
    projectId: 'photofiesta',
    storageBucket: 'photofiesta.appspot.com',
    iosBundleId: 'com.example.photofiesta.RunnerTests',
  );
}
